FROM golang:1.9-alpine as build
WORKDIR /go/src/github.com/danp/catchbus
COPY . .
RUN go install ./cmd/gtfs-api

FROM alpine:3.6
RUN apk add --no-cache tzdata
RUN adduser -D -h /app app
WORKDIR /app
USER app
RUN mkdir /app/bin
COPY --from=build /go/bin/gtfs-api /app/bin

EXPOSE 5000
